version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        links:
            - fpm
        volumes:
            - .:/var/www/bd
            - ./images/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        working_dir:
            /var/www/bd


    fpm:
        build: ./images/php-fpm
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/bd
        working_dir:
            /var/www/bd
